import Image from "next/image";
import { TemplateNav } from "./TemplateNav";
import { HeroMedia } from "./HeroMedia";

const teaCards=[
  ["01","Golden Pearl","HANDMADE SPECIALITY TEA","A handmade speciality Assam tea from Nahorchukbari, remembered for its ₹99,999/kg auction achievement in 2022.","/images/teahouse/product-1.jpg","#golden-pearl"],
  ["02","Ekarotoli Clonal","REGISTERED TEA MARK","AFT Tea Factory is associated with the registered tea mark Ekoratoli Clonal.","/images/teahouse/product-2.jpg","#contact"],
  ["03","Assam Black Teas","BOLD AROMA · DISTINCTIVE CHARACTER","Black teas crafted from Assam leaf, with the character of the region at their core.","/images/teahouse/product-3.jpg","#contact"],
] as const;

export function TeaHouseHome(){return <><TemplateNav/><main>
  <section id="home" className="th-hero"><HeroMedia/><div className="th-hero-overlay"/><div className="th-container th-hero-content"><p>ASSAM TEA · DIBRUGARH · INDIA</p><h1>Extraordinary<span className="mobile-break"><br/></span> Teas<br/><span>from an<span className="mobile-break"><br/></span> Extraordinary Land</span></h1><div className="th-hero-copy">Rooted in the tea-growing landscape of Dibrugarh, AFT Techno Trade works with small growers to craft distinctive Assam teas shaped by the land, the leaf and the people behind them.</div><div className="th-actions"><a href="#teas" className="th-button light">Discover Our Teas</a><a href="#story" className="th-button outline">Our Story</a></div></div><a className="th-next" href="#story" aria-label="Explore story">↓</a></section>
  <section id="story" className="th-section th-story-bento"><div className="th-container"><div className="story-bento"><article className="bento-landscape"><Image src="/images/aft/assam-dawn.png" alt="Misty tea gardens in Assam" fill sizes="(max-width: 760px) 100vw, 42vw"/><span>01 / THE LAND</span></article><article className="bento-intro"><p className="bento-kicker">OUR STORY</p><h2>From Small Tea Growers<br/>to a Remarkable Cup</h2><p>AFT Techno Trade began in Dibrugarh with people who understood the work behind every leaf. Rooted in small tea growing, the business grew around a network of growers and a simple ambition: Assam teas with greater character and distinction.</p><a href="#golden-pearl">Our journey <b>↗</b></a></article><article className="bento-detail"><Image src="/images/teahouse/about-4.jpg" alt="Pouring tea" fill sizes="(max-width: 760px) 50vw, 21vw"/><span>02 / THE LEAF</span></article><article className="bento-people"><p className="bento-kicker">BUILT BY PEOPLE WHO KNOW THE LEAF</p><h3>Knowledge grown from the ground up.</h3><p>Founded by Noor Alam Khan, Imran Khan and Aslam Khan, AFT grew from a background in small tea growing. Commercial production began in 2019.</p></article><article className="bento-craft"><Image src="/images/teahouse/about-3.jpg" alt="Tea leaf detail" fill sizes="(max-width: 760px) 50vw, 21vw"/><span>03 / THE CRAFT</span></article></div></div></section>
  <section id="golden-pearl" className="th-feature"><div className="th-container pearl-layout"><div className="pearl-visual"><div className="pearl-image-wrap"><Image src="/images/teahouse/product-1.jpg" alt="Golden Pearl speciality tea leaves" fill sizes="(max-width: 900px) 100vw, 46vw"/></div><p>NAHORCHUKBARI · ASSAM</p><span className="pearl-mark">GP<br/><i>01</i></span></div><div className="pearl-content"><p className="pearl-kicker">A HISTORIC AUCTION MILESTONE</p><h2>Golden Pearl</h2><div className="pearl-price"><strong>₹99,999</strong><span>/ KG</span></div><div className="pearl-rule"/><p className="pearl-meta">GUWAHATI TEA AUCTION CENTRE <b/> FEBRUARY 2022</p><p className="pearl-copy">Handmade in Nahorchukbari near Dibrugarh Airport, Golden Pearl is a speciality Assam tea that became a defining moment for AFT Techno Trade.</p><p className="pearl-copy">In February 2022, one kilogram achieved ₹99,999 at the Guwahati Tea Auction Centre, matching what was then the country&apos;s highest tea-auction price.</p><a href="#golden-story" className="pearl-link">Discover Golden Pearl <b>→</b></a></div></div></section>
  <section id="teas" className="th-product"><div className="th-container"><div className="th-title centered"><p>OUR TEAS</p><h2>Distinctive Assam Teas<br/>with Character</h2></div><p className="tea-intro">Our teas reflect the diversity of Assam&apos;s leaf — from handmade speciality tea to distinctive black teas rooted in the Dibrugarh region.</p><div className="th-product-grid">{teaCards.map(([num,title,description,copy,src,href])=><a className="th-product-card" href={href} key={title}><div className="th-product-image"><Image src={src} alt={title} fill sizes="(max-width: 800px) 100vw, 33vw"/></div><div className="th-product-box"><small>{num} · {description}</small><h3>{title}</h3><p>{copy}</p><span>{title === "Golden Pearl" ? "Discover Golden Pearl" : "Explore Tea"} →</span></div></a>)}</div></div></section>
  <section id="craft" className="th-promo"><div className="th-container th-promo-grid"><div><div className="th-title"><p>OUR CRAFT</p><h2>Care in Every Leaf.</h2></div><p>Good tea begins long before the cup. It begins with the leaf, the grower and the decisions made along the way. Working closely with small growers, AFT focuses on careful selection and speciality tea production while respecting the character of Assam&apos;s leaf.</p><div className="th-process"><span>GROW</span><b>→</b><span>SELECT</span><b>→</b><span>CRAFT</span><b>→</b><span>REFINE</span><b>→</b><span>BREW</span></div></div><div className="th-promo-panel"><p>FROM ASSAM, WITH CARE</p><a href="#buyers" className="th-play">→</a></div></div></section>
  <section id="origin" className="th-origin"><Image src="/images/aft/assam-dawn.png" alt="Assam tea plantation" fill sizes="100vw"/><div className="th-origin-overlay"/><div className="th-container th-origin-copy"><div className="th-title"><p>THE LAND</p><h2>Born in Dibrugarh.<br/>Shaped by Assam.</h2></div><p>From the tea-growing landscapes around Dibrugarh, AFT&apos;s teas carry the character of the region where they begin.</p><div className="th-places"><span>DIBRUGARH</span><i/><span>DIKOM</span><i/><span>LAHOWAL</span><i/><span>NAHORCHUKBARI</span><i/><span>EKORATOLI</span></div></div></section>
  <section id="golden-story" className="th-section th-timeline"><div className="th-container"><div className="th-title centered"><p>THE STORY OF GOLDEN PEARL</p><h2>A Tea Worth Remembering.</h2></div><p className="timeline-intro">Some teas become memorable because of how they taste. Others become part of a place&apos;s story. Golden Pearl became one of AFT Techno Trade&apos;s defining moments.</p><div className="th-timeline-list"><span>NAHORCHUKBARI<br/><small>DIBRUGARH, ASSAM</small></span><b>↓</b><span>HANDMADE SPECIALITY TEA</span><b>↓</b><span>GUWAHATI TEA AUCTION CENTRE</span><b>↓</b><strong>₹99,999/KG <small>FEBRUARY 2022</small></strong></div><p className="timeline-close">The achievement reflected AFT&apos;s ambition: to take Assam&apos;s tea-growing tradition and create speciality teas capable of standing apart.</p></div></section>
  <section id="buyers" className="th-buyers"><Image src="/images/aft/assam-dawn.png" alt="Assam tea garden in warm light" fill sizes="100vw"/><div className="th-buyers-overlay"/><div className="th-container th-buyers-copy"><p>FOR BUYERS, DISTRIBUTORS & PARTNERS</p><h2>From Dibrugarh<br/>to the World.</h2><div>From speciality teas to distinctive Assam black teas, AFT welcomes conversations with buyers, distributors and partners looking for teas with a clear sense of origin.<br/><br/>Tell us what you&apos;re looking for, and let&apos;s start a conversation.</div><a href="#contact" className="th-button light">Enquire Now</a></div></section>
</main><TemplateFooter/></>}

function TemplateFooter(){const links=[['Our Story','#story'],['Our Teas','#teas'],['Our Craft','#craft'],['Golden Pearl','#golden-pearl'],['For Buyers','#buyers']];return <footer id="contact" className="th-footer"><div className="footer-watermark" aria-hidden>ASSAM<br/>AFT</div><div className="th-container modern-footer"><div className="footer-top"><div className="footer-brand"><span>AFT /</span><h3>TECHNO TRADE</h3><p>AFT TEA FACTORY · DIBRUGARH, ASSAM</p></div><a className="footer-cta" href="mailto:hello@aftteafactory.com"><em>Partner with AFT</em><span>Start a conversation</span><b>↗</b></a></div><div className="footer-main"><div className="footer-intro"><p>Premium Assam teas, crafted with small tea growers at the heart of every leaf.</p><div className="footer-tags"><span>EST. 2019</span><span>DIKOM · LAHOWAL</span></div><address>Dibrugarh, Assam<br/>India</address></div><nav className="footer-links">{links.map(([label,href],index)=><a href={href} key={href}><small>0{index+1}</small>{label}<b>↗</b></a>)}</nav><div className="footer-note"><small>FOR BUYERS & PARTNERS</small><p>For enquiries about distinctive Assam teas, Golden Pearl, and partnership opportunities.</p><div className="footer-dot-row"><i/><i/><i/></div></div></div></div><div className="th-copyright"><div className="th-container">© 2026 AFT TECHNO TRADE <span>FROM DIBRUGARH TO THE WORLD</span></div></div></footer>}
